# Get data based on a particular invoice item
GET http://localhost:4000/api/invoice_items/1

###
# Create an Invoice Item
POST http://localhost:4000/api/invoice_items/
Content-Type: application/json

{"invoice_item": {
  "amount": 2600,
  "description": "API Test Invoice Item"
}, "invoice": 1}