# List all organizations
GET http://localhost:4000/api/organizations/

###
# Get all Invoice Items for a particular Invoice
GET http://localhost:4000/api/organizations/1/invoices

###
# Get data based on a particular organization
GET http://localhost:4000/api/organizations/1

###
# Create an organization
POST http://localhost:4000/api/organizations/
Content-Type: application/json

{"organization": {
  "name": "Jvenom",
  "stripe_customer_id": "cus_987"
}}

###
# Update an organization
PUT  http://localhost:4000/api/organizations/2
Content-Type: application/json

{"organization": {
  "stripe_customer_id": "cus_456"
}}

###
# Delete an organization
DELETE   http://localhost:4000/api/organizations/2